version: "2"
services:
  yoga_service:
    container_name: yoga_service
    restart: always
    build: .
    ports:
      - "3001:3000"

  mongo-seed:
    build:
      context: .
      dockerfile: mongo-seed/Dockerfile

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
